routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'confirm' => false,
    'verify' => false,
    'reset' => false,
]);
Route::group(['namespace' => 'Auth'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('auth.login');
    Route::get('/logout', 'LoginController@logout')->name('get.logout');
});

$groupData = [
    'namespace' => 'Shop\Admin',
    'prefix' => 'admin',
    'middleware' => 'auth',
];
Route::group($groupData, function () {
    $methods = ['index', 'edit', 'store', 'create', 'update'];
    Route::get('/', 'IndexController@index');
    /*Категории*/
    Route::resource('/categories', 'CategoryController')->only($methods)->names('shop.admin.categories');
    Route::match(['get', 'post'], '/categories/add-image', ['uses' => 'CategoryController@addImage', 'as' => 'shop.admin.categories.addImage']);
    Route::get('/categories/delete{id}', ['uses' => 'CategoryController@deleteCategory', 'as' => 'shop.admin.categories.deleteCategory']);
    /*Товары*/
    Route::resource('/products', 'ProductsController')->only($methods)->names('shop.admin.products');
    Route::match(['get', 'post'], '/products/add-image', ['uses' => 'ProductsController@addImage', 'as' => 'shop.admin.products.addImage']);
    Route::get('/products/delete{id}', ['uses' => 'ProductsController@deleteProduct', 'as' => 'shop.admin.products.deleteProduct']);
    Route::get('/products/deleteitem{id}', ['uses' => 'ProductsController@deleteItem', 'as' => 'shop.admin.products.deleteItem']);
    Route::get('/products/{alias}', ['uses' => 'ProductsController@list', 'as' => 'shop.admin.products.list']);
    /*Навигация*/
    Route::resource('/navigation', 'NavigationController')->only($methods)->names('shop.admin.navigation');
    Route::get('/navigation/delete{id}', ['uses' => 'NavigationController@deleteNavigation', 'as' => 'shop.admin.navigation.deleteNavigation']);
    Route::match(['get', 'post'], '/navigation/add-image', ['uses' => 'NavigationController@addImage', 'as' => 'shop.admin.navigation.addImage']);
    /*Слайдер*/
    Route::resource('/sliders', 'SlidersController')->only($methods)->names('shop.admin.sliders');
    Route::get('/sliders/delete{id}', ['uses' => 'SlidersController@deleteSlider', 'as' => 'shop.admin.sliders.deleteSlider']);
    Route::match(['get', 'post'], '/sliders/add-image', ['uses' => 'SlidersController@addImage', 'as' => 'shop.admin.sliders.addImage']);
    /*Блог*/
    Route::resource('/blog', 'BlogController')->only($methods)->names('shop.admin.blog');
    Route::get('/blog/delete{id}', ['uses' => 'BlogController@deleteArticle', 'as' => 'shop.admin.blog.deleteArticle']);
    Route::match(['get', 'post'], '/blog/add-image', ['uses' => 'BlogController@addImage', 'as' => 'shop.admin.blog.addImage']);
});

/*Клиентская часть*/
Route::group(['namespace' => 'Shop'], function () {
    $methods = ['index'];
    $methodsCategories = ['index'];
    $methodsProducts = ['show'];
    $methodsCart = ['show', 'store', 'index'];
    $methodsContacts = ['store', 'index'];
    $methodsBlog = ['show', 'index'];

    Route::resource('/', 'MainController')
        ->names('shop.main')
        ->only($methods);

    Route::resource('/products', 'ProductsController', [
        'parameters' => [
            'products' => 'alias',
        ]
    ])->only($methodsProducts);

    Route::resource('/contacts', 'ContactsController')
        ->names('contacts')
        ->only($methodsContacts);

    Route::resource('/menu', 'CategoriesController', [
        'parameters' => [
            'menu' => 'alias',
        ]
    ])->only($methodsCategories);

    Route::resource('/blog', 'BlogController')
        ->names('blog')
        ->only($methodsBlog);

    Route::get('/cart/checkout', ['uses' => 'CartController@checkout', 'as' => 'cart.checkout']);
    Route::get('/cart/clear', ['uses' => 'CartController@clear', 'as' => 'cart.clear']);
    Route::get('/cart/delete', ['uses' => 'CartController@delete', 'as' => 'cart.delete']);
    Route::resource('/cart', 'CartController', [
        'parameters' => [
            'cart' => 'id',
        ]
    ])->names('cart')
        ->only($methodsCart);

    Route::get('/product/{alias}', ['uses' => 'ProductsController@showProduct', 'as' => 'product.info']);

    Route::get('/search/result', ['uses' => 'SearchController@index', 'as' => 'products.result']);
    Route::get('/autocomplete', ['uses' => 'SearchController@search', 'as' => 'products.search']);
    Route::get('/searchBlog/result', ['uses' => 'SearchBlogController@index', 'as' => 'blog.result']);
    Route::get('/autocompleteBlog', ['uses' => 'SearchBlogController@search', 'as' => 'blog.search']);

    Route::match(['get', 'post'], '/about', ['uses' => 'AboutController@index', 'as' => 'about.index']);
});

app/Http/Controllers/Shop/AboutController.php
<?php

namespace App\Http\Controllers\Shop;

use Arr;

/**
 * Class AboutController.
 * Страница О нас.
 */
class AboutController extends BaseController
{
    /**
     * Конструктор.
     */
    public function __construct()
    {
        parent::__construct();

        $this->template = env('THEME') . '.shop.about.about';
    }

    /**
     * Контентная часть.
     */
    public function index()
    {
        $content = view(env('THEME') . '.shop.about.aboutContent');
        $this->vars = Arr::add($this->vars, 'content', $content);

        $this->title = 'Кафе Северное Сияние | О нашем уютном кафе | Доставка';
        $this->description = 'Доставка обедов по Санкт-Петербургу и Ленинградской области кафе Северное Сияние, доставка обедов на предприятия';
        $this->keywords = 'доставка, обеды на предприятия, заказ на дом, кафе Северное Сияние, европейская кухня, морепродукты';

        return $this->renderOutput();
    }
}

app/Http/Controllers/Shop/Admin/BaseController.php
<?php

namespace App\Http\Controllers\Shop\Admin;

use App\Http\Controllers\Controller;
use Arr;
use Auth;
use Illuminate\Http\Request;
use Menu;

/**
 * Class BaseController.
 *
 * Базовый контроллер Администратора.
 */
abstract class BaseController extends Controller
{
    /**
     * Метатеги.
     */
    protected $title;

    /**
     * Репозиторий.
     *
     * Логика работы с блогом.
     */
    protected $blog_rep;

    /**
     * Репозиторий.
     *
     * Логика работы со слайдером.
     */
    protected $slider_rep;

    /**
     * Репозиторий.
     *
     * Логика работы со слайдером.
     */
    protected $menu_rep;

    /**
     * Репозиторий.
     *
     * Логика работы с продуктами.
     */
    protected $products_rep;

    /**
     * Репозиторий.
     *
     * Логика работы с категориями.
     */
    protected $category_rep;

    /**
     * Подключаемый шаблон.
     */
    protected $template;

    /**
     * Массив переменных передаваемых в шаблон.
     */
    protected $vars = [];

    /**
     * Обьект. User
     */
    protected $user;

    /**
     * Область контента.
     */
    protected $content = false;

    public function __construct()
    {
        //
    }

    /**
     * Рендер шаблона.
     */
    public function renderOutput()
    {
        $this->vars = Arr::add($this->vars, 'title', $this->title);

        $navigation = view(env('THEME') . '.shop.admin.navigation');
        $this->vars = Arr::add($this->vars, 'navigation', $navigation);

        if($this->content){
            $this->vars = Arr::add($this->vars, 'content', $this->content);
        }

        $footer = view(env('THEME') . '.shop.admin.footer');
        $this->vars = Arr::add($this->vars, 'footer', $footer);

        return view($this->template)->with($this->vars);
    }
}

app/Http/Controllers/Shop/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Shop\Admin;

use App\Http\Requests\ShopBlogCreateRequest;
use App\Http\Requests\ShopBlogUpdateRequest;
use App\Models\ShopBlog;
use App\Repositories\ShopBlogRepository;
use Arr;
use Config;
use Illuminate\Http\Request;

/**
 * Class BlogController.
 * Список статей блога | Создание | Редактирование | Удаление
 */
class BlogController extends BaseController
{
    /**
     * @var ShopBlogRepository
     */
    public function __construct()
    {
        parent::__construct();
        $this->blog_rep = app(ShopBlogRepository::class);
        $this->template = env('THEME') . '.shop.admin.blog.index';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $this->title = 'Список статей';
        $paginator = $this->blog_rep->getAllWithPaginate(Config::get('settings.paginateBlogAdmin'));

        $content = view(env('THEME') . '.shop.admin.blog.contentBlog', compact('paginator'));
        $this->vars = Arr::add($this->vars, 'content', $content);

        return $this->renderOutput();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $item = new ShopBlog();
        $this->title = 'Новая статья';

        $content = view(env('THEME') . '.shop.admin.blog.add', compact('item'));
        $this->vars = Arr::add($this->vars, 'content', $content);
        return $this->renderOutput();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ShopBlogCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ShopBlogCreateRequest $request)
    {
        $data = $request->all();

        $item = (new ShopBlog())->create($data);
        $this->blog_rep->getImg($item);
        $save = $item->save();
        if ($save) {
            return redirect()
                ->route('shop.admin.blog.create')
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Ошибка сохранения'])
                ->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $item = $this->blog_rep->getEdit($id);

        if (empty($item)) {
            abort('404');
        }

        $content = view(env('THEME') . '.shop.admin.blog.edit', compact('item'));
        $this->vars = Arr::add($this->vars, 'content', $content);
        $this->title = "Редактирование статьи '$item->title'";

        return $this->renderOutput();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ShopBlogUpdateRequest $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ShopBlogUpdateRequest $request, $id)
    {
        $item = $this->blog_rep->getEdit($id);
        if (empty($item)) {
            return back()/*Редирект на пред. страницу*/
                ->withErrors(['msg' => "Запись id = [{$id}] не найдена"])
                ->withInput();
        }

        $data = $request->all();
        $this->blog_rep->getImg($item);
        $result = $item->update($data);

        if ($result) {
            return redirect()
                ->route('shop.admin.blog.edit', $item->id)// Куда редирект
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()/*Редирект на пред. страницу*/
                ->withErrors(['msg' => 'Ошибка сохранения'])/*Выкидываем ошибку*/
                ->withInput(); /*Оставляем данные в полях формы*/
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function deleteArticle($id)
    {
        if ($id) {
            $db = $this->blog_rep->deleteFromDB($id);

            if ($db) {
                return redirect()
                    ->route('shop.admin.blog.index')// Куда редирект
                    ->with(['success' => 'Статья успешно удалена']);
            } else {
                return back()/*Редирект на пред. страницу*/
                    ->withErrors(['msg' => 'Ошибка сохранения'])/*Выкидываем ошибку*/
                    ->withInput(); /*Оставляем данные в полях формы*/
            }
        }
    }

    /**
     * Ajax Upload Single Image.
     */
    public function addImage()
    {
        if (isset($_GET['upload'])) {
            if ($_POST['name'] == 'singleBlog') {
                $wmax = Config::get('settings.img_blog_width');
                $hmax = Config::get('settings.img_blog_height');
            }
            $name = $_POST['name'];
            $this->blog_rep->uploadImg($name, $wmax, $hmax);
        }
    }
}

app/Http/Controllers/Shop/Admin/IndexController.php
<?php

namespace App\Http\Controllers\Shop\Admin;

use App\Repositories\ShopBlogRepository;
use App\Repositories\ShopCategoryRepository;
use App\Repositories\ShopProductRepository;
use App\Repositories\ShopSlidersRepository;
use Arr;
use Illuminate\Http\Request;

/**
 * Class IndexController.
 * Главная страница Панели Администратора.
 */
class IndexController extends BaseController
{
    /**
     * @var ShopCategoryRepository
     */
    public function __construct()
    {
        parent::__construct();
        $this->category_rep = app(ShopCategoryRepository::class);
        $this->products_rep = app(ShopProductRepository::class);
        $this->blog_rep = app(ShopBlogRepository::class);
        $this->slider_rep = app(ShopSlidersRepository::class);

        $this->template = env('THEME') . '.shop.admin.index';
    }

    /**
     * Вывод главной страница Админ Панели.
     */
    public function index()
    {
        $this->title = 'Панель Администратора';

        $countCategories = $this->category_rep->countCategories();
        $countProducts = $this->products_rep->countProducts();
        $countArticles = $this->blog_rep->countArticles();
        $getSlider = $this->slider_rep->getSlider();
        $lastArticle = $this->blog_rep->lastPosts();

        $categories = $this->category_rep->getCategoriesMenu();

        $content = view(env('THEME') . '.shop.admin.main_content', compact('countCategories', 'countProducts', 'countArticles', 'getSlider', 'categories', 'lastArticle'));
        $this->vars = Arr::add($this->vars, 'content', $content);

        return $this->renderOutput();
    }
}

app/Http/Controllers/Shop/BlogController.php
<?php

namespace App\Http\Controllers\Shop;

use App\Http\Controllers\Controller;
use App\Repositories\ShopBlogRepository;
use Arr;
use Config;
use Illuminate\Http\Request;

/**
 * Class BlogController
 * Страница Блога | Информация о статье блога .
 */
class BlogController extends BaseController
{
    /**
     * Конструктор.
     */
    public function __construct()
    {
        parent::__construct();
        $this->template = env('THEME') . '.shop.blog.blog';
    }

    /**
     * Контентная часть.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @var ShopBlogRepository $posts
     */
    public function index()
    {
        $posts = $this->blog_rep->getPosts(Config::get('settings.paginateBlog'));
        $content = view(env('THEME') . '.shop.blog.blogContent', compact('posts'));
        $this->vars = Arr::add($this->vars, 'content', $content);

        $this->title = 'Кафе Северное Сияние | Блог';
        $this->description = 'Интерессные новости о кулинарии';
        $this->keywords = 'Новости, кулинария, что поесть, где поесть';

        return $this->renderOutput();
    }

    /**
     * Инфонрмация об одной статье.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @var ShopBlogRepository $post
     */
    public function show($alias)
    {
        $post = $this->blog_rep->onePost($alias);
        if(!$post) {
            abort(404);
        }

        $content = view(env('THEME') . '.shop.blog.post', compact('post'));
        $this->vars = Arr::add($this->vars, 'content', $content);

        $this->title = 'Блог |' . ' ' . $post->title;
        $this->description = $post->description;
        $this->keywords = $post->keywords;

        return $this->renderOutput();
    }
}

resources/views/auroraborealis/shop/admin/footer.blade.php
<footer class="main-footer">
    <strong>Северное Сияние &copy; 2019-2020
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> 1.0.1
    </div>
</footer>

resources/views/auroraborealis/shop/admin/index.blade.php
@extends(env('THEME').'.layouts.admin')

@section('navigation')
    {!! $navigation !!}
@endsection

@section('content')
    {!! $content !!}
@endsection

@section('footer')
    {!! $footer !!}
@endsection

resources/views/auroraborealis/shop/admin/main_content.blade.php
<div class="row">
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-info">
            <div class="inner">
                <h3>{{ $countCategories }}</h3>
                <p>Категории</p>
            </div>
            <div class="icon">
                <i class="ion ion-bag"></i>
            </div>
            <a href="{{ route('shop.admin.categories.index') }}" class="small-box-footer">Просмотр категорий <i
                    class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-success">
            <div class="inner">
                <h3>{{ $countProducts }}<sup style="font-size: 20px">%</sup></h3>

                <p>Товары</p>
            </div>
            <div class="icon">
                <i class="ion ion-stats-bars"></i>
            </div>
            <a href="{{ route('shop.admin.products.index') }}" class="small-box-footer">Просмотр товаров<i
                    class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <div class="col-lg-3 col-6">
        <!-- small box -->
        <div class="small-box bg-danger">
            <div class="inner">
                <h3>{{ $countArticles }}</h3>

                <p>Блог</p>
            </div>
            <div class="icon">
                <i class="ion ion-pie-graph"></i>
            </div>
            <a href="{{ route('shop.admin.blog.index') }}" class="small-box-footer">Просмотр статей <i
                    class="fas fa-arrow-circle-right"></i></a>
        </div>
    </div>
    <!-- ./col -->
</div>
<div class="col-md-12">
    <div class="card card-primary">
        <div class="card-header">
            <div class="card-title">
                Слайды на главной
            </div>
        </div>
        <div class="card-body">
            <div class="row">
                @if(count($getSlider) > 0)
                    @foreach($getSlider as $slide)
                        <div class="col-sm-4">
                            <a href="{{route('shop.admin.sliders.edit', $slide->id)}}" data-toggle="lightbox"
                               data-title="sample 11 - white" data-gallery="gallery">
                                <img src="{{ asset(env('THEME')) }}/img/{{ $slide->img }}" class="img-fluid mb-2"
                                     alt="white sample">
                            </a>
                        </div>
                    @endforeach
                @else
                    <div class="alert alert-info alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-info"></i> Ошибка!</h5>
                        Не добавлен не один слайд.
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Меню</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <ul class="products-list product-list-in-card pl-2 pr-2">
                    @if(count($categories) > 0)
                        @foreach($categories as $category)
                            <li class="item">
                                <div class="product-img">
                                    <img src="{{ asset(env('THEME')) }}/img/menu/{{ $category->img }}"
                                         alt="{{ $category->title }}" class="img-size-50">
                                </div>
                                <div class="product-info">
                                    <a href="{{ route('shop.admin.products.list', ['alias' => $category->alias]) }}">{{ $category->title }}
                                    </a><a href="{{route('shop.admin.categories.edit', $category->id)}}"><i
                                            class="fas fa-pencil-alt"></i></a>
                                    <span class="product-description">
                        {{ $category->excerpt }}
                      </span>
                                </div>
                            </li>
                    @endforeach
                @else

                @endif
                <!-- /.item -->
                </ul>
            </div>
            <!-- /.card-body -->
            <div class="card-footer text-center">
                <a href="{{ route('shop.admin.categories.index') }}" class="uppercase">Просмотр всех категорий</a>
            </div>
            <!-- /.card-footer -->
        </div>
    </div>
    <div class="col-md-6">
        <!-- Box Comment -->
        <div class="card card-widget">
            <div class="card-header">
                <h3 class="card-title">Последние записи блога</h3>
                <!-- /.user-block -->
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse"><i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove"><i class="fas fa-times"></i>
                    </button>
                </div>
                <!-- /.card-tools -->
            </div>
            <!-- /.card-header -->
            <div class="card-body">
            @if(count($lastArticle) > 0)
                @foreach($lastArticle as $article)
                <!-- Attachment -->
                    <div class="attachment-block clearfix">
                        <img class="attachment-img" src="{{ asset(env('THEME')) }}/img/blog/{{ $article->img }}" alt="{{ $article->title }}">

                        <div class="attachment-pushed">
                            <h4 class="attachment-heading"><a href="http://www.lipsum.com/">{{ $article->title }}</a></h4>

                            <div class="attachment-text">
                                {!! \Illuminate\Support\Str::limit($article->content, 127, ' ') !!}<br/><a
                                    href="#">Редактировать статью</a>
                            </div>
                            <!-- /.attachment-text -->
                        </div>
                        <!-- /.attachment-pushed -->
                    </div>
                    <!-- /.attachment-block -->
                @endforeach
                @else
                    <div class="attachment-block clearfix">
                        <img class="attachment-img" src="{{ asset(env('THEME')) }}/img/blog/no_image.jpg" alt="">

                        <div class="attachment-pushed">
                            <h4 class="attachment-heading">Новых статей нет...</h4>
                            <!-- /.attachment-text -->
                        </div>
                        <!-- /.attachment-pushed -->
                    </div>
                @endif
            </div>
            <!-- /.card-body -->
            <!-- /.card-footer -->
            <div class="card-footer">
                <a href="#">Просмотр всех статей</a>
            </div>
            <!-- /.card-footer -->
        </div>
        <!-- /.card -->
    </div>
</div>

resources/views/auroraborealis/shop/admin/navigation.blade.php
<nav class="mt-2">
    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        {{--Главная--}}
        <li class="nav-item">
            <a href="{{ url('admin') }}" class="nav-link">
                <i class="nav-icon fas fas fa-box-open"></i>
                <p>Главная</p>
            </a>
        </li>
        {{--Категории--}}
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="nav-icon fab fa-buffer"></i>
                <p>
                    Категории
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('shop.admin.categories.index') }}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Список категорий</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('shop.admin.categories.create') }}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Добавить категорию</p>
                    </a>
                </li>
            </ul>
        </li>
        {{--Товары--}}
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="nav-icon fa fa-shopping-bag"></i>
                <p>
                    Товары
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('shop.admin.products.index') }}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Список товаров</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('shop.admin.products.create') }}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Добавить товар</p>
                    </a>
                </li>
            </ul>
        </li>
        {{--Навигация--}}
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="nav-icon fa fa-cog"></i>
                <p>
                    Навигация
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('shop.admin.navigation.index') }}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Список меню</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('shop.admin.navigation.create') }}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Добавить меню</p>
                    </a>
                </li>
            </ul>
        </li>
        {{--Слайдер--}}
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="nav-icon fa fa-plus-square"></i>
                <p>
                    Слайдер
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('shop.admin.sliders.index') }}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Все слайдеры</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('shop.admin.sliders.create') }}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Добавить слайд</p>
                    </a>
                </li>
            </ul>
        </li>
        {{--Блог--}}
        <li class="nav-item has-treeview">
            <a href="#" class="nav-link">
                <i class="nav-icon fa fa-paper-plane"></i>
                <p>
                    Блог
                    <i class="right fas fa-angle-left"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="{{ route('shop.admin.blog.index') }}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Все статьи</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="{{ route('shop.admin.blog.create') }}" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Добавить статью</p>
                    </a>
                </li>
            </ul>
        </li>
    </ul>
</nav>