routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'confirm' => false,
    'verify' => false,
    'reset' => false,
]);
Route::group(['namespace' => 'Auth'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('auth.login');
    Route::get('/logout', 'LoginController@logout')->name('get.logout');
});

$groupData = [
    'namespace' => 'Shop\Admin',
    'prefix' => 'admin',
    'middleware' => 'auth',
];
Route::group($groupData, function () {
    $methods = ['index', 'edit', 'store', 'create', 'update'];
    Route::get('/', 'IndexController@index');
    /*Категории*/
    Route::resource('/categories', 'CategoryController')->only($methods)->names('shop.admin.categories');
    Route::match(['get', 'post'], '/categories/add-image', ['uses' => 'CategoryController@addImage', 'as' => 'shop.admin.categories.addImage']);
    Route::get('/categories/delete{id}', ['uses' => 'CategoryController@deleteCategory', 'as' => 'shop.admin.categories.deleteCategory']);
    /*Товары*/
    Route::resource('/products', 'ProductsController')->only($methods)->names('shop.admin.products');
    Route::match(['get', 'post'], '/products/add-image', ['uses' => 'ProductsController@addImage', 'as' => 'shop.admin.products.addImage']);
    Route::get('/products/delete{id}', ['uses' => 'ProductsController@deleteProduct', 'as' => 'shop.admin.products.deleteProduct']);
    Route::get('/products/deleteitem{id}', ['uses' => 'ProductsController@deleteItem', 'as' => 'shop.admin.products.deleteItem']);
    Route::get('/products/{alias}', ['uses' => 'ProductsController@list', 'as' => 'shop.admin.products.list']);
    /*Навигация*/
    Route::resource('/navigation', 'NavigationController')->only($methods)->names('shop.admin.navigation');
    Route::get('/navigation/delete{id}', ['uses' => 'NavigationController@deleteNavigation', 'as' => 'shop.admin.navigation.deleteNavigation']);
    Route::match(['get', 'post'], '/navigation/add-image', ['uses' => 'NavigationController@addImage', 'as' => 'shop.admin.navigation.addImage']);
    /*Слайдер*/
    Route::resource('/sliders', 'SlidersController')->only($methods)->names('shop.admin.sliders');
    Route::get('/sliders/delete{id}', ['uses' => 'SlidersController@deleteSlider', 'as' => 'shop.admin.sliders.deleteSlider']);
    Route::match(['get', 'post'], '/sliders/add-image', ['uses' => 'SlidersController@addImage', 'as' => 'shop.admin.sliders.addImage']);
    /*Блог*/
    Route::resource('/blog', 'BlogController')->only($methods)->names('shop.admin.blog');
    Route::get('/blog/delete{id}', ['uses' => 'BlogController@deleteArticle', 'as' => 'shop.admin.blog.deleteArticle']);
    Route::match(['get', 'post'], '/blog/add-image', ['uses' => 'BlogController@addImage', 'as' => 'shop.admin.blog.addImage']);
});

/*Клиентская часть*/
Route::group(['namespace' => 'Shop'], function () {
    $methods = ['index'];
    $methodsCategories = ['index'];
    $methodsProducts = ['show'];
    $methodsCart = ['show', 'store', 'index'];
    $methodsContacts = ['store', 'index'];
    $methodsBlog = ['show', 'index'];

    Route::resource('/', 'MainController')
        ->names('shop.main')
        ->only($methods);

    Route::resource('/products', 'ProductsController', [
        'parameters' => [
            'products' => 'alias',
        ]
    ])->only($methodsProducts);

    Route::resource('/contacts', 'ContactsController')
        ->names('contacts')
        ->only($methodsContacts);

    Route::resource('/menu', 'CategoriesController', [
        'parameters' => [
            'menu' => 'alias',
        ]
    ])->only($methodsCategories);

    Route::resource('/blog', 'BlogController')
        ->names('blog')
        ->only($methodsBlog);

    Route::get('/cart/checkout', ['uses' => 'CartController@checkout', 'as' => 'cart.checkout']);
    Route::get('/cart/clear', ['uses' => 'CartController@clear', 'as' => 'cart.clear']);
    Route::get('/cart/delete', ['uses' => 'CartController@delete', 'as' => 'cart.delete']);
    Route::resource('/cart', 'CartController', [
        'parameters' => [
            'cart' => 'id',
        ]
    ])->names('cart')
        ->only($methodsCart);

    Route::get('/product/{alias}', ['uses' => 'ProductsController@showProduct', 'as' => 'product.info']);

    Route::get('/search/result', ['uses' => 'SearchController@index', 'as' => 'products.result']);
    Route::get('/autocomplete', ['uses' => 'SearchController@search', 'as' => 'products.search']);
    Route::get('/searchBlog/result', ['uses' => 'SearchBlogController@index', 'as' => 'blog.result']);
    Route::get('/autocompleteBlog', ['uses' => 'SearchBlogController@search', 'as' => 'blog.search']);

    Route::match(['get', 'post'], '/about', ['uses' => 'AboutController@index', 'as' => 'about.index']);
});

app/Http/Controllers/Shop/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Shop\Admin;

use App\Http\Requests\ShopCategoryCreateRequest;
use App\Http\Requests\ShopCategoryUpdateRequest;
use App\Models\ShopCategory;
use App\Repositories\ShopCategoryRepository;
use Arr;
use Config;
use Illuminate\Http\Request;
use Str;
use Validator;

/**
 * Class CategoryController.
 * Список категории | Создание | Редактирование | Удаление
 */
class CategoryController extends BaseController
{
    /**
     * @var ShopCategoryRepository
     */
    public function __construct()
    {
        parent::__construct();
        $this->category_rep = app(ShopCategoryRepository::class);
        $this->template = env('THEME') . '.shop.admin.categories.index';
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $this->title = 'Список категорий';
        $paginator = $this->category_rep->getAllWithPaginate(Config::get('settings.paginateCategoryAdmin'));

        $content = view(env('THEME') . '.shop.admin.categories.contentCategory', compact('paginator'));
        $this->vars = Arr::add($this->vars, 'content', $content);

        return $this->renderOutput();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $item = new ShopCategory();
        $this->title = 'Новая категория';

        $categoryList = $this->category_rep->getForComboBox();
        $content = view(env('THEME') . '.shop.admin.categories.add', compact('categoryList', 'item'));
        $this->vars = Arr::add($this->vars, 'content', $content);
        return $this->renderOutput();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ShopCategoryCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ShopCategoryCreateRequest $request)
    {
        $data = $request->all();

        $item = (new ShopCategory())->create($data);
        $this->category_rep->getImg($item);
        $save = $item->save();
        if ($save) {
            return redirect()
                ->route('shop.admin.categories.create')
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Ошибка сохранения'])
                ->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $item = $this->category_rep->getEdit($id);

        if (empty($item)) {
            abort('404');
        }

        $content = view(env('THEME') . '.shop.admin.categories.edit', compact('item'));
        $this->vars = Arr::add($this->vars, 'content', $content);
        $this->title = "Редактирование $item->title";

        return $this->renderOutput();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ShopCategoryUpdateRequest $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ShopCategoryUpdateRequest $request, $id)
    {
        $item = $this->category_rep->getEdit($id);
        if (empty($item)) {
            return back()/*Редирект на пред. страницу*/
            ->withErrors(['msg' => "Запись id = [{$id}] не найдена"])
                ->withInput();
        }

        $data = $request->all();
        $this->category_rep->getImg($item);
        $result = $item->update($data);

        if ($result) {
            return redirect()
                ->route('shop.admin.categories.edit', $item->id)// Куда редирект
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()/*Редирект на пред. страницу*/
            ->withErrors(['msg' => 'Ошибка сохранения'])/*Выкидываем ошибку*/
            ->withInput(); /*Оставляем данные в полях формы*/
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function deleteCategory($id)
    {
        if ($id) {
            $db = $this->category_rep->deleteFromDB($id);

            if ($db) {
                return redirect()
                    ->route('shop.admin.categories.index')// Куда редирект
                    ->with(['success' => 'Категория успешно удалена']);
            } else {
                return back()/*Редирект на пред. страницу*/
                ->withErrors(['msg' => 'Ошибка сохранения'])/*Выкидываем ошибку*/
                ->withInput(); /*Оставляем данные в полях формы*/
            }
        }
    }

    /**
     * Ajax Upload Single Image.
     */
    public function addImage()
    {
        if (isset($_GET['upload'])) {
            if ($_POST['name'] == 'single') {
                $wmax = Config::get('settings.img_width');
                $hmax = Config::get('settings.img_height');
            }
            $name = $_POST['name'];
            $this->category_rep->uploadImg($name, $wmax, $hmax);
        }
    }
}

app/Http/Controllers/Shop/CategoriesController.php
<?php

namespace App\Http\Controllers\Shop;

use App\Repositories\ShopCategoryRepository;
use Arr;
use Config;

/**
 * Class CategoriesController
 *
 * Категории.Меню.
 */
class CategoriesController extends BaseController
{
    /**
     * Class CategoriesController
     *
     * Конструктор.
     */
    public function __construct()
    {
        parent::__construct();
        $this->template = env('THEME') . '.shop.menu.menu';
    }

    /**
     * Главная страница меню.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @var ShopCategoryRepository $categories
     */
    public function index()
    {
        $this->title = 'Кафе Северное Сияние | Меню';
        $this->description = 'Доставка обедов по Санкт-Петербургу и Ленинградской области кафе Северное Сияние, доставка обедов на предприятия';
        $this->keywords = 'доставка, обеды на предприятия, заказ на дом, кафе Северное Сияние';

        $categories = $this->category_rep->getCategoriesMenu(Config::get('settings.paginateMenuPage'));
        $content = view(env('THEME') . '.shop.menu.menuContent',compact('categories'));
        $this->vars = Arr::add($this->vars, 'content', $content);

        return $this->renderOutput();
    }
}

resources/views/auroraborealis/shop/admin/categories/add.blade.php
<form method="POST" action="{{ route('shop.admin.categories.store') }}" data-toggle="validator" role="form">
    @csrf
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @include(env('THEME') . '.shop.admin.categories.includes.item_add_main_col')
            </div>
            <div class="col-md-3">
                <br>
                <div class="row justify-content-center">
                    @include(env('THEME') . '.shop.admin.categories.includes.item_add_col')
                </div>
            </div>
        </div>
    </div>
</form>

resources/views/auroraborealis/shop/admin/categories/contentCategory.blade.php
    <div class="col-md-12">
        <a class="btn btn-primary" href="{{route('shop.admin.categories.create')}}">Добавить</a>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Категория</th>
                    <th style="text-align: right">Удалить</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($paginator as $item)
                    @php /** @var \App\Models\ShopCategory $item  */ @endphp
                    <tr>
                        <td>{{$item->id}}</td>
                        <td><a href="{{route('shop.admin.categories.edit', $item->id)}}">{{$item->title}}</a></td>
                        <td style="text-align: right"><a href=" {{ route('shop.admin.categories.deleteCategory', $item->id) }} " class="btn btn-danger delete"><i class="fas fa-trash"></i></a></td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    {{--Пагинация--}}
    @if($paginator->total() > $paginator->count())
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    {{ $paginator->links() }}
                </div>
            </div>
        </div>
    @endif
    {{--Конец пагинации--}}

resources/views/auroraborealis/shop/admin/categories/edit.blade.php
@php /** @var \App\Models\ShopCategory $item  */ @endphp
<form method="POST" action="{{ route('shop.admin.categories.update', $item->id) }}" data-toggle="validator" role="form">
    @method('PATCH')
        @csrf
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    @include(env('THEME') . '.shop.admin.categories.includes.item_edit_main_col')
                </div>
                <div class="col-md-3">
                    @include(env('THEME') . '.shop.admin.categories.includes.item_edit_add_col')
                </div>
            </div>
        </div>
    </form>

resources/views/auroraborealis/shop/admin/categories/index.blade.php
@extends(env('THEME').'.layouts.admin')

@section('navigation')
    {!! $navigation !!}
@endsection

@section('content')
    {!! $content !!}
@endsection

@section('footer')
    {!! $footer !!}
@endsection