routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'confirm' => false,
    'verify' => false,
    'reset' => false,
]);
Route::group(['namespace' => 'Auth'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('auth.login');
    Route::get('/logout', 'LoginController@logout')->name('get.logout');
});

$groupData = [
    'namespace' => 'Shop\Admin',
    'prefix' => 'admin',
    'middleware' => 'auth',
];
Route::group($groupData, function () {
    $methods = ['index', 'edit', 'store', 'create', 'update'];
    Route::get('/', 'IndexController@index');
    /*Категории*/
    Route::resource('/categories', 'CategoryController')->only($methods)->names('shop.admin.categories');
    Route::match(['get', 'post'], '/categories/add-image', ['uses' => 'CategoryController@addImage', 'as' => 'shop.admin.categories.addImage']);
    Route::get('/categories/delete{id}', ['uses' => 'CategoryController@deleteCategory', 'as' => 'shop.admin.categories.deleteCategory']);
    /*Товары*/
    Route::resource('/products', 'ProductsController')->only($methods)->names('shop.admin.products');
    Route::match(['get', 'post'], '/products/add-image', ['uses' => 'ProductsController@addImage', 'as' => 'shop.admin.products.addImage']);
    Route::get('/products/delete{id}', ['uses' => 'ProductsController@deleteProduct', 'as' => 'shop.admin.products.deleteProduct']);
    Route::get('/products/deleteitem{id}', ['uses' => 'ProductsController@deleteItem', 'as' => 'shop.admin.products.deleteItem']);
    Route::get('/products/{alias}', ['uses' => 'ProductsController@list', 'as' => 'shop.admin.products.list']);
    /*Навигация*/
    Route::resource('/navigation', 'NavigationController')->only($methods)->names('shop.admin.navigation');
    Route::get('/navigation/delete{id}', ['uses' => 'NavigationController@deleteNavigation', 'as' => 'shop.admin.navigation.deleteNavigation']);
    Route::match(['get', 'post'], '/navigation/add-image', ['uses' => 'NavigationController@addImage', 'as' => 'shop.admin.navigation.addImage']);
    /*Слайдер*/
    Route::resource('/sliders', 'SlidersController')->only($methods)->names('shop.admin.sliders');
    Route::get('/sliders/delete{id}', ['uses' => 'SlidersController@deleteSlider', 'as' => 'shop.admin.sliders.deleteSlider']);
    Route::match(['get', 'post'], '/sliders/add-image', ['uses' => 'SlidersController@addImage', 'as' => 'shop.admin.sliders.addImage']);
    /*Блог*/
    Route::resource('/blog', 'BlogController')->only($methods)->names('shop.admin.blog');
    Route::get('/blog/delete{id}', ['uses' => 'BlogController@deleteArticle', 'as' => 'shop.admin.blog.deleteArticle']);
    Route::match(['get', 'post'], '/blog/add-image', ['uses' => 'BlogController@addImage', 'as' => 'shop.admin.blog.addImage']);
});

/*Клиентская часть*/
Route::group(['namespace' => 'Shop'], function () {
    $methods = ['index'];
    $methodsCategories = ['index'];
    $methodsProducts = ['show'];
    $methodsCart = ['show', 'store', 'index'];
    $methodsContacts = ['store', 'index'];
    $methodsBlog = ['show', 'index'];

    Route::resource('/', 'MainController')
        ->names('shop.main')
        ->only($methods);

    Route::resource('/products', 'ProductsController', [
        'parameters' => [
            'products' => 'alias',
        ]
    ])->only($methodsProducts);

    Route::resource('/contacts', 'ContactsController')
        ->names('contacts')
        ->only($methodsContacts);

    Route::resource('/menu', 'CategoriesController', [
        'parameters' => [
            'menu' => 'alias',
        ]
    ])->only($methodsCategories);

    Route::resource('/blog', 'BlogController')
        ->names('blog')
        ->only($methodsBlog);

    Route::get('/cart/checkout', ['uses' => 'CartController@checkout', 'as' => 'cart.checkout']);
    Route::get('/cart/clear', ['uses' => 'CartController@clear', 'as' => 'cart.clear']);
    Route::get('/cart/delete', ['uses' => 'CartController@delete', 'as' => 'cart.delete']);
    Route::resource('/cart', 'CartController', [
        'parameters' => [
            'cart' => 'id',
        ]
    ])->names('cart')
        ->only($methodsCart);

    Route::get('/product/{alias}', ['uses' => 'ProductsController@showProduct', 'as' => 'product.info']);

    Route::get('/search/result', ['uses' => 'SearchController@index', 'as' => 'products.result']);
    Route::get('/autocomplete', ['uses' => 'SearchController@search', 'as' => 'products.search']);
    Route::get('/searchBlog/result', ['uses' => 'SearchBlogController@index', 'as' => 'blog.result']);
    Route::get('/autocompleteBlog', ['uses' => 'SearchBlogController@search', 'as' => 'blog.search']);

    Route::match(['get', 'post'], '/about', ['uses' => 'AboutController@index', 'as' => 'about.index']);
});

app/Http/Controllers/Shop/Admin/BlogController.php
<?php

namespace App\Http\Controllers\Shop\Admin;

use App\Http\Requests\ShopBlogCreateRequest;
use App\Http\Requests\ShopBlogUpdateRequest;
use App\Models\ShopBlog;
use App\Repositories\ShopBlogRepository;
use Arr;
use Config;
use Illuminate\Http\Request;

/**
 * Class BlogController.
 * Список статей блога | Создание | Редактирование | Удаление
 */
class BlogController extends BaseController
{
    /**
     * @var ShopBlogRepository
     */
    public function __construct()
    {
        parent::__construct();
        $this->blog_rep = app(ShopBlogRepository::class);
        $this->template = env('THEME') . '.shop.admin.blog.index';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $this->title = 'Список статей';
        $paginator = $this->blog_rep->getAllWithPaginate(Config::get('settings.paginateBlogAdmin'));

        $content = view(env('THEME') . '.shop.admin.blog.contentBlog', compact('paginator'));
        $this->vars = Arr::add($this->vars, 'content', $content);

        return $this->renderOutput();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $item = new ShopBlog();
        $this->title = 'Новая статья';

        $content = view(env('THEME') . '.shop.admin.blog.add', compact('item'));
        $this->vars = Arr::add($this->vars, 'content', $content);
        return $this->renderOutput();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ShopBlogCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ShopBlogCreateRequest $request)
    {
        $data = $request->all();

        $item = (new ShopBlog())->create($data);
        $this->blog_rep->getImg($item);
        $save = $item->save();
        if ($save) {
            return redirect()
                ->route('shop.admin.blog.create')
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()
                ->withErrors(['msg' => 'Ошибка сохранения'])
                ->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $item = $this->blog_rep->getEdit($id);

        if (empty($item)) {
            abort('404');
        }

        $content = view(env('THEME') . '.shop.admin.blog.edit', compact('item'));
        $this->vars = Arr::add($this->vars, 'content', $content);
        $this->title = "Редактирование статьи '$item->title'";

        return $this->renderOutput();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ShopBlogUpdateRequest $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ShopBlogUpdateRequest $request, $id)
    {
        $item = $this->blog_rep->getEdit($id);
        if (empty($item)) {
            return back()/*Редирект на пред. страницу*/
                ->withErrors(['msg' => "Запись id = [{$id}] не найдена"])
                ->withInput();
        }

        $data = $request->all();
        $this->blog_rep->getImg($item);
        $result = $item->update($data);

        if ($result) {
            return redirect()
                ->route('shop.admin.blog.edit', $item->id)// Куда редирект
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()/*Редирект на пред. страницу*/
                ->withErrors(['msg' => 'Ошибка сохранения'])/*Выкидываем ошибку*/
                ->withInput(); /*Оставляем данные в полях формы*/
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function deleteArticle($id)
    {
        if ($id) {
            $db = $this->blog_rep->deleteFromDB($id);

            if ($db) {
                return redirect()
                    ->route('shop.admin.blog.index')// Куда редирект
                    ->with(['success' => 'Статья успешно удалена']);
            } else {
                return back()/*Редирект на пред. страницу*/
                    ->withErrors(['msg' => 'Ошибка сохранения'])/*Выкидываем ошибку*/
                    ->withInput(); /*Оставляем данные в полях формы*/
            }
        }
    }

    /**
     * Ajax Upload Single Image.
     */
    public function addImage()
    {
        if (isset($_GET['upload'])) {
            if ($_POST['name'] == 'singleBlog') {
                $wmax = Config::get('settings.img_blog_width');
                $hmax = Config::get('settings.img_blog_height');
            }
            $name = $_POST['name'];
            $this->blog_rep->uploadImg($name, $wmax, $hmax);
        }
    }
}

app/Http/Controllers/Shop/BlogController.php
<?php

namespace App\Http\Controllers\Shop;

use App\Http\Controllers\Controller;
use App\Repositories\ShopBlogRepository;
use Arr;
use Config;
use Illuminate\Http\Request;

/**
 * Class BlogController
 * Страница Блога | Информация о статье блога .
 */
class BlogController extends BaseController
{
    /**
     * Конструктор.
     */
    public function __construct()
    {
        parent::__construct();
        $this->template = env('THEME') . '.shop.blog.blog';
    }

    /**
     * Контентная часть.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @var ShopBlogRepository $posts
     */
    public function index()
    {
        $posts = $this->blog_rep->getPosts(Config::get('settings.paginateBlog'));
        $content = view(env('THEME') . '.shop.blog.blogContent', compact('posts'));
        $this->vars = Arr::add($this->vars, 'content', $content);

        $this->title = 'Кафе Северное Сияние | Блог';
        $this->description = 'Интерессные новости о кулинарии';
        $this->keywords = 'Новости, кулинария, что поесть, где поесть';

        return $this->renderOutput();
    }

    /**
     * Инфонрмация об одной статье.
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * @var ShopBlogRepository $post
     */
    public function show($alias)
    {
        $post = $this->blog_rep->onePost($alias);
        if(!$post) {
            abort(404);
        }

        $content = view(env('THEME') . '.shop.blog.post', compact('post'));
        $this->vars = Arr::add($this->vars, 'content', $content);

        $this->title = 'Блог |' . ' ' . $post->title;
        $this->description = $post->description;
        $this->keywords = $post->keywords;

        return $this->renderOutput();
    }
}

resources/views/auroraborealis/shop/admin/blog/add.blade.php
<form method="POST" action="{{ route('shop.admin.blog.store') }}" data-toggle="validator" role="form">
    @csrf
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @include(env('THEME') . '.shop.admin.blog.includes.item_add_main_col')
            </div>
            <div class="col-md-3">
                <br>
                <div class="row justify-content-center">
                    @include(env('THEME') . '.shop.admin.blog.includes.item_add_col')
                </div>
            </div>
        </div>
    </div>
</form>

resources/views/auroraborealis/shop/admin/blog/contentBlog.blade.php
<div class="col-md-12">
    <a class="btn btn-primary" href="{{route('shop.admin.blog.create')}}">Добавить</a>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Название статьи</th>
                <th>Создана</th>
                <th>Опубликована</th>
                <th style="text-align: right">Удалить</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($paginator as $item)
                @php /** @var \App\Models\ShopBlog $item  */ @endphp
                <tr>
                    <td>{{$item->id}}</td>
                    <td><a href="{{route('shop.admin.blog.edit', $item->id)}}">{{$item->title}}</a></td>
                    <td>{{ $item->created_at }}</td>
                    <td>{{ $item->published_at }}</td>
                    <td style="text-align: right"><a
                            href=" {{ route('shop.admin.blog.deleteArticle', $item->id) }} "
                            class="btn btn-danger delete"><i class="fas fa-trash"></i></a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>
{{--Пагинация--}}
@if($paginator->total() > $paginator->count())
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                {{ $paginator->links() }}
            </div>
        </div>
    </div>
@endif
{{--Конец пагинации--}}

resources/views/auroraborealis/shop/admin/blog/edit.blade.php
@php /** @var \App\Models\ShopBlog $item  */ @endphp
<form method="POST" action="{{ route('shop.admin.blog.update', $item->id) }}" data-toggle="validator" role="form">
    @method('PATCH')
    @csrf
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @include(env('THEME') . '.shop.admin.blog.includes.item_edit_main_col')
            </div>
            <div class="col-md-3">
                @include(env('THEME') . '.shop.admin.blog.includes.item_edit_add_col')
            </div>
        </div>
    </div>
</form>

resources/views/auroraborealis/shop/admin/blog/index.blade.php
@extends(env('THEME').'.layouts.admin')

@section('navigation')
    {!! $navigation !!}
@endsection

@section('content')
    {!! $content !!}
@endsection

@section('footer')
    {!! $footer !!}
@endsection