routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'confirm' => false,
    'verify' => false,
    'reset' => false,
]);
Route::group(['namespace' => 'Auth'], function () {
    Route::get('/login', 'LoginController@showLoginForm')->name('login');
    Route::post('/login', 'LoginController@login')->name('auth.login');
    Route::get('/logout', 'LoginController@logout')->name('get.logout');
});

$groupData = [
    'namespace' => 'Shop\Admin',
    'prefix' => 'admin',
    'middleware' => 'auth',
];
Route::group($groupData, function () {
    $methods = ['index', 'edit', 'store', 'create', 'update'];
    Route::get('/', 'IndexController@index');
    /*Категории*/
    Route::resource('/categories', 'CategoryController')->only($methods)->names('shop.admin.categories');
    Route::match(['get', 'post'], '/categories/add-image', ['uses' => 'CategoryController@addImage', 'as' => 'shop.admin.categories.addImage']);
    Route::get('/categories/delete{id}', ['uses' => 'CategoryController@deleteCategory', 'as' => 'shop.admin.categories.deleteCategory']);
    /*Товары*/
    Route::resource('/products', 'ProductsController')->only($methods)->names('shop.admin.products');
    Route::match(['get', 'post'], '/products/add-image', ['uses' => 'ProductsController@addImage', 'as' => 'shop.admin.products.addImage']);
    Route::get('/products/delete{id}', ['uses' => 'ProductsController@deleteProduct', 'as' => 'shop.admin.products.deleteProduct']);
    Route::get('/products/deleteitem{id}', ['uses' => 'ProductsController@deleteItem', 'as' => 'shop.admin.products.deleteItem']);
    Route::get('/products/{alias}', ['uses' => 'ProductsController@list', 'as' => 'shop.admin.products.list']);
    /*Навигация*/
    Route::resource('/navigation', 'NavigationController')->only($methods)->names('shop.admin.navigation');
    Route::get('/navigation/delete{id}', ['uses' => 'NavigationController@deleteNavigation', 'as' => 'shop.admin.navigation.deleteNavigation']);
    Route::match(['get', 'post'], '/navigation/add-image', ['uses' => 'NavigationController@addImage', 'as' => 'shop.admin.navigation.addImage']);
    /*Слайдер*/
    Route::resource('/sliders', 'SlidersController')->only($methods)->names('shop.admin.sliders');
    Route::get('/sliders/delete{id}', ['uses' => 'SlidersController@deleteSlider', 'as' => 'shop.admin.sliders.deleteSlider']);
    Route::match(['get', 'post'], '/sliders/add-image', ['uses' => 'SlidersController@addImage', 'as' => 'shop.admin.sliders.addImage']);
    /*Блог*/
    Route::resource('/blog', 'BlogController')->only($methods)->names('shop.admin.blog');
    Route::get('/blog/delete{id}', ['uses' => 'BlogController@deleteArticle', 'as' => 'shop.admin.blog.deleteArticle']);
    Route::match(['get', 'post'], '/blog/add-image', ['uses' => 'BlogController@addImage', 'as' => 'shop.admin.blog.addImage']);
});

/*Клиентская часть*/
Route::group(['namespace' => 'Shop'], function () {
    $methods = ['index'];
    $methodsCategories = ['index'];
    $methodsProducts = ['show'];
    $methodsCart = ['show', 'store', 'index'];
    $methodsContacts = ['store', 'index'];
    $methodsBlog = ['show', 'index'];

    Route::resource('/', 'MainController')
        ->names('shop.main')
        ->only($methods);

    Route::resource('/products', 'ProductsController', [
        'parameters' => [
            'products' => 'alias',
        ]
    ])->only($methodsProducts);

    Route::resource('/contacts', 'ContactsController')
        ->names('contacts')
        ->only($methodsContacts);

    Route::resource('/menu', 'CategoriesController', [
        'parameters' => [
            'menu' => 'alias',
        ]
    ])->only($methodsCategories);

    Route::resource('/blog', 'BlogController')
        ->names('blog')
        ->only($methodsBlog);

    Route::get('/cart/checkout', ['uses' => 'CartController@checkout', 'as' => 'cart.checkout']);
    Route::get('/cart/clear', ['uses' => 'CartController@clear', 'as' => 'cart.clear']);
    Route::get('/cart/delete', ['uses' => 'CartController@delete', 'as' => 'cart.delete']);
    Route::resource('/cart', 'CartController', [
        'parameters' => [
            'cart' => 'id',
        ]
    ])->names('cart')
        ->only($methodsCart);

    Route::get('/product/{alias}', ['uses' => 'ProductsController@showProduct', 'as' => 'product.info']);

    Route::get('/search/result', ['uses' => 'SearchController@index', 'as' => 'products.result']);
    Route::get('/autocomplete', ['uses' => 'SearchController@search', 'as' => 'products.search']);
    Route::get('/searchBlog/result', ['uses' => 'SearchBlogController@index', 'as' => 'blog.result']);
    Route::get('/autocompleteBlog', ['uses' => 'SearchBlogController@search', 'as' => 'blog.search']);

    Route::match(['get', 'post'], '/about', ['uses' => 'AboutController@index', 'as' => 'about.index']);
});

app/Http/Controllers/Shop/Admin/NavigationController.php
<?php

namespace App\Http\Controllers\Shop\Admin;

use App\Http\Requests\ShopMenuCreateRequest;
use App\Http\Requests\ShopMenuUpdateRequest;
use App\Models\ShopMenu;
use App\Repositories\ShopMenuRepository;
use Arr;
use Config;
use Illuminate\Http\Request;

/**
 * Class NavigationController.
 * Навигация Меню.
 */
class NavigationController extends BaseController
{

    public function __construct()
    {
        parent::__construct();
        $this->menu_rep = app(ShopMenuRepository::class);
        $this->template = env('THEME') . '.shop.admin.navigation.index';
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $this->title = 'Навигация';

        $menu = $this->menu_rep->getMenu();
        $content = view(env('THEME') . '.shop.admin.navigation.contentNavigation', compact('menu'));
        $this->vars = Arr::add($this->vars, 'content', $content);

        return $this->renderOutput();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $item = new ShopMenu();
        $this->title = 'Новый пункт меню';

        $content = view(env('THEME') . '.shop.admin.navigation.add', compact('item'));
        $this->vars = Arr::add($this->vars, 'content', $content);
        return $this->renderOutput();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param ShopMenuCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ShopMenuCreateRequest $request)
    {
        $data = $request->all();

        $item = (new ShopMenu())->create($data);
        //dd($data);
        $this->menu_rep->getImg($item);
        $save = $item->save();
        if ($save) {
            return redirect()
                ->route('shop.admin.navigation.create')
                ->with(['success' => 'Пункт меню добавлен']);
        } else {
            return back()
                ->withErrors(['msg' => 'Ошибка сохранения'])
                ->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $item = $this->menu_rep->getEdit($id);

        if (empty($item)) {
            abort('404');
        }

        $content = view(env('THEME') . '.shop.admin.navigation.edit', compact('item'));
        $this->vars = Arr::add($this->vars, 'content', $content);
        $this->title = "Редактирование $item->title";

        return $this->renderOutput();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param ShopMenuUpdateRequest $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ShopMenuUpdateRequest $request, $id)
    {
        $item = $this->menu_rep->getEdit($id);
        if (empty($item)) {
            return back()/*Редирект на пред. страницу*/
                ->withErrors(['msg' => "Запись id = [{$id}] не найдена"])
                ->withInput();
        }

        $data = $request->all();
        $this->menu_rep->getImg($item);
        $result = $item->update($data);

        if ($result) {
            return redirect()
                ->route('shop.admin.navigation.edit', $item->id)// Куда редирект
                ->with(['success' => 'Успешно сохранено']);
        } else {
            return back()/*Редирект на пред. страницу*/
            ->withErrors(['msg' => 'Ошибка сохранения'])/*Выкидываем ошибку*/
            ->withInput(); /*Оставляем данные в полях формы*/
        }
    }

    /**
     * Удаление пункта меню.
     */
    public function deleteNavigation()
    {
        //
    }

    /**
     * Ajax Upload Single Image.
     */
    public function addImage()
    {
        if (isset($_GET['upload'])) {
            if ($_POST['name'] == 'singleMenu') {
                $wmax = Config::get('settings.img_menu_width');
                $hmax = Config::get('settings.img_menu_height');
            }
            $name = $_POST['name'];
            $this->menu_rep->uploadImg($name, $wmax, $hmax);
        }
    }
}

resources/views/auroraborealis/shop/admin/navigation/add.blade.php
<form method="POST" action="{{ route('shop.admin.navigation.store') }}" data-toggle="validator" role="form">
    @csrf
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @include(env('THEME') . '.shop.admin.navigation.includes.item_add_main_col')
            </div>
            <div class="col-md-3">
                <br>
                <div class="row justify-content-center">
                    @include(env('THEME') . '.shop.admin.navigation.includes.item_add_col')
                </div>
            </div>
        </div>
    </div>
</form>

resources/views/auroraborealis/shop/admin/navigation/contentNavigation.blade.php
<div class="col-md-12">
    <a class="btn btn-primary" href="{{route('shop.admin.navigation.create')}}">Добавить</a>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Наименование</th>
                <th>Путь</th>
                <th style="text-align: right">Удалить</th>
            </tr>
            </thead>
            <tbody>
            @foreach ($menu as $item)
                @php /** @var \App\Models\ShopMenu $item  */ @endphp
                <tr>
                    <td>{{$item->id}}</td>
                    <td><a href="{{route('shop.admin.navigation.edit', $item->id)}}">{{$item->title}}</a></td>
                    <td><a href="{{route('shop.admin.navigation.edit', $item->id)}}">{{$item->path}}</a></td>
                    <td style="text-align: right"><a
                            href=" {{ route('shop.admin.navigation.deleteNavigation', $item->id) }} "
                            class="btn btn-danger delete"><i class="fas fa-trash"></i></a></td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
</div>

resources/views/auroraborealis/shop/admin/navigation/edit.blade.php
@php /** @var \App\Models\ShopMenu $item  */ @endphp
<form method="POST" action="{{ route('shop.admin.navigation.update', $item->id) }}" data-toggle="validator" role="form">
    @method('PATCH')
    @csrf
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @include(env('THEME') . '.shop.admin.navigation.includes.item_edit_main_col')
            </div>
            <div class="col-md-3">
                @include(env('THEME') . '.shop.admin.navigation.includes.item_edit_add_col')
            </div>
        </div>
    </div>
</form>

resources/views/auroraborealis/shop/admin/navigation/index.blade.php
@extends(env('THEME').'.layouts.admin')

@section('navigation')
    {!! $navigation !!}
@endsection

@section('content')
    {!! $content !!}
@endsection

@section('footer')
    {!! $footer !!}
@endsection